version: "3" # mettre la version de compose

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    env_file: .env         # indique le fichier optionnel contenant l'environnement
    depends_on:
      - wordpress
    ports:
      - "443:443"
     volume:
      - wordpress_files
    network:
      - inception
    restart: always     

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file: .env    
    ports:
    - "80:80"
    volume:
      - wordpress_files
    network:
      - inception
    depends_on:
      - mariadb
    restart: always 
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file: .env
    volume:
      - db_data
    network:
      - inception  
    restart: always
  
  volume:
    - wordpress_files: /var/www/html
    - db_data: /var/lib/mysql

  network:
    - inception

